language: cpp
sudo: required
dist: precise

env:
  global:
    - secure: "TapRYOiHJernTcqUHu5i71V62TvdoyV6DDl3c4ViCmm0TJy2mHM5D9EJaRyoxP3uGw6dYx6k5FQeSuh/1pIv9NQjngg4SrRE8NeH6Lj+RI98XhwWPFseqBQA55a9fmxHKczTtsHz/Xvkq57EA4qb3g8poR9NrKfeo0UoOpFlhTOuxbzx/ugFrQImYDF4abjnhrlo+8d4F0HH20Na0zoLEzj+htdYq7GKHGDKXlVZOHJ+MWZv6U7E7hNcAwS39JlP0KgWfp6khO4T8tDXEY5w/aAQydeyL3beHgXocVwGpj4LLT6W7gJ9u2Fmx3R2ZfgNTe5IcWy+7J8NCxiNZP5EmlErjysEJpY/0EkAlao7PDnf95XMnUMg3uahG+X7KDUQ8xi9fW4BhiDv53TLxJt5Iax6GdSigUPpYN6vlQOrGZFwRzO5nSJdYyU/A2PTnp1H8AfW2YwFTaOKULYNSlEEcvKltZgpYqYhLK2M2qdHLwYggc2ZW9EbRDYIcgElSK3JGnBwzXcuyLspnXGDsau/QehTmA4bFOAMS6+2XkKEmhyUtMRBUi1jTIYdwLlVz+3i5gi8mLDcUgp0nVW9MHbXwju86sLgql/R9LZfiU19kpcfgNtZ2nJbhstn0/yHxwx8oxilSIWcpTncEAdB4hJBex5+LUeJ15jJtB2DMwZKNIM="

matrix:
  include:
    - compiler: icc
      env:
        - COMPILER=icc
        - INSTR_SET=scalar
      before_install:
        - wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh' |  /bin/sh
        - source ~/.bashrc
      after_script:
        - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
    - compiler: icc
      env:
        - COMPILER=icc
        - INSTR_SET=avx
      before_install:
        - wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh' |  /bin/sh
        - source ~/.bashrc
      after_script:
        - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
    - compiler: icc
      env:
        - COMPILER=icc
        - INSTR_SET=avx2
      before_install:
        - wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh' |  /bin/sh
        - source ~/.bashrc
      after_script:
        - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
    - compiler: icc
      env:
        - COMPILER=icc
        - INSTR_SET=mic_avx512
      before_install:
        - wget -q -O /dev/stdout 'https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh' |  /bin/sh
        - source ~/.bashrc
      after_script:
        - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER=g++-4.9
        - INSTR_SET=scalar
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - COMPILER=g++-4.9
        - INSTR_SET=avx
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - INSTR_SET=scalar
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - INSTR_SET=avx
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - COMPILER=g++-5
        - INSTR_SET=avx2
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
        - INSTR_SET=scalar
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
        - INSTR_SET=avx
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - COMPILER=g++-6
        - INSTR_SET=avx2
# No g++6.3 with avx512 compatible binutils available on travis.
# disabling configurations for now
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env:
#        - COMPILER=g++-6
#        - INSTR_SET=mic_avx512
#    - compiler: gcc
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - g++-6
#      env:
#        - COMPILER=g++-6
#        - INSTR_SET=core_avx512
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: 
        - COMPILER=clang++-3.6
        - INSTR_SET=scalar
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: 
        - COMPILER=clang++-3.6
        - INSTR_SET=avx
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: 
        - COMPILER=clang++-3.6
        - INSTR_SET=avx2
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - INSTR_SET=scalar
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - INSTR_SET=avx
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: 
        - COMPILER=clang++-3.7
        - INSTR_SET=avx2
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: 
        - COMPILER=clang++-3.8
        - INSTR_SET=scalar
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: 
        - COMPILER=clang++-3.8
        - INSTR_SET=avx
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
      env: 
        - COMPILER=clang++-3.8
        - INSTR_SET=avx2
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - INSTR_SET=scalar
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - INSTR_SET=avx
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - INSTR_SET=avx2
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - INSTR_SET=mic_avx512
    - compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main"
              key_url: "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.9
      env: 
        - COMPILER=clang++-3.9
        - INSTR_SET=core_avx512

script:
  - cd microbenchmarks
  - chmod +x build_tests.sh
  - ./build_tests.sh $COMPILER $INSTR_SET release
  - cd ../unittest
  - make CXX=$COMPILER ISA=$INSTR_SET BUILD=debug

